export const metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <article className="prose prose-invert mx-auto max-w-3xl py-10 text-ink-100">
      <h1 className="text-3xl font-black">Privacy Policy</h1>
      <p className="text-sm text-ink-400">Operator: Unipath · kanjivision.app</p>
      <h2 className="mt-6 text-xl font-bold">What we collect</h2>
      <ul>
        <li>Account email (for auth and receipts).</li>
        <li>Study progress (SRS state, streak) — stored locally, optionally synced.</li>
        <li>Billing metadata returned by Paddle / TossPayments.</li>
      </ul>
      <h2 className="mt-6 text-xl font-bold">AI generation</h2>
      <p>
        Mnemonics and example sentences are generated by Anthropic Claude. We
        do not send personal data to the model, only the target word.
      </p>
      <h2 className="mt-6 text-xl font-bold">Your rights</h2>
      <p>Email <code>support@kanjivision.app</code> to export or delete your data.</p>
      <p className="mt-8 text-xs text-ink-400">Placeholder — finalize before launch.</p>
    </article>
  );
}
